# Generated by Django 6.1.1 on 2026-09-07 09:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('phone', models.CharField(max_length=40, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='اسلاگ')),
                ('summary', models.CharField(max_length=300, verbose_name='خلاصه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(default='building', help_text='یکی از: building، crane، ruler، wrench، hardhat، leaf', max_length=40, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='REN', max_length=120, verbose_name='نام شرکت')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='شعار')),
                ('about', models.TextField(blank=True, verbose_name='درباره ما')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='سال سابقه')),
                ('projects_done', models.PositiveIntegerField(default=0, verbose_name='پروژه تکمیل\u200cشده')),
                ('area_built', models.PositiveIntegerField(default=0, verbose_name='متراژ ساخته\u200cشده')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=180, unique=True, verbose_name='اسلاگ')),
                ('category', models.CharField(choices=[('residential', 'مسکونی'), ('commercial', 'تجاری'), ('industrial', 'صنعتی'), ('renovation', 'بازسازی')], default='residential', max_length=20, verbose_name='دسته\u200cبندی')),
                ('status', models.CharField(choices=[('completed', 'تکمیل\u200cشده'), ('ongoing', 'در حال اجرا'), ('planned', 'در دست طراحی')], default='completed', max_length=20, verbose_name='وضعیت')),
                ('summary', models.CharField(max_length=300, verbose_name='خلاصه')),
                ('description', models.TextField(blank=True, verbose_name='شرح پروژه')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='موقعیت')),
                ('client', models.CharField(blank=True, max_length=160, verbose_name='کارفرما')),
                ('area_m2', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='متراژ (متر مربع)')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال')),
                ('cover', models.ImageField(blank=True, upload_to='projects/', verbose_name='تصویر شاخص')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order', '-year', '-id'],
                'indexes': [models.Index(fields=['is_featured', 'order'], name='main_projec_is_feat_ece6ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر پروژه',
                'verbose_name_plural': 'تصاویر پروژه',
                'ordering': ['order', 'id'],
            },
        ),
    ]
