# Generated by Django 6.1.1 on 2026-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='تصویر پس\u200cزمینه صفحه اصلی. با اسکرول از بالای تصویر تا پایین آن حرکت می\u200cکند، پس عکس عمودی و بلند بهترین نتیجه را می\u200cدهد. اگر خالی بماند، به\u200cجای عکس یک برج سه\u200cبعدی نمایش داده می\u200cشود.', upload_to='hero/', verbose_name='تصویر صفحه اصلی'),
        ),
    ]
