# Generated by Django 6.1.1 on 2026-09-07 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitesettings_hero_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'İletişim mesajı', 'verbose_name_plural': 'İletişim mesajları'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-year', '-id'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Proje görseli', 'verbose_name_plural': 'Proje görselleri'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site ayarları', 'verbose_name_plural': 'Site ayarları'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Gönderim tarihi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Okundu'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Konu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='area_m2',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Alan (m²)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('residential', 'Konut'), ('commercial', 'Ticari'), ('industrial', 'Endüstriyel'), ('renovation', 'Renovasyon')], default='residential', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=160, verbose_name='İşveren'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, upload_to='projects/', verbose_name='Kapak görseli'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kayıt tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Proje açıklaması'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Ana sayfada göster'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=160, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=180, unique=True, verbose_name='Kısa ad'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Tamamlandı'), ('ongoing', 'Devam ediyor'), ('planned', 'Tasarım aşamasında')], default='completed', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=300, verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Yıl'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/gallery/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.project', verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='building', help_text='Şunlardan biri: building, crane, ruler, wrench, hardhat, leaf', max_length=40, verbose_name='Simge'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='Kısa ad'),
        ),
        migrations.AlterField(
            model_name='service',
            name='summary',
            field=models.CharField(max_length=300, verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about',
            field=models.TextField(blank=True, verbose_name='Hakkımızda'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='area_built',
            field=models.PositiveIntegerField(default=0, verbose_name='İnşa edilen alan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='REN', max_length=120, verbose_name='Şirket adı'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Ana sayfanın arka plan görseli. Kaydırdıkça görselin üstünden altına doğru hareket eder, bu yüzden dikey ve uzun fotoğraflar en iyi sonucu verir. Boş bırakılırsa görsel yerine 3B bir kule gösterilir.', upload_to='hero/', verbose_name='Ana sayfa görseli'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='projects_done',
            field=models.PositiveIntegerField(default=0, verbose_name='Tamamlanan proje'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Yıl deneyim'),
        ),
    ]
