# Generated by Django 6.1.1 on 2026-09-07 14:50

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contactmessage_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('title_en', models.CharField(blank=True, max_length=120, verbose_name='Başlık (EN)')),
                ('description', models.CharField(max_length=300, verbose_name='Açıklama')),
                ('description_en', models.CharField(blank=True, max_length=300, verbose_name='Açıklama (EN)')),
                ('duration', models.CharField(blank=True, help_text='ör. 2-4 hafta', max_length=60, verbose_name='Süre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Süreç adımı',
                'verbose_name_plural': 'Süreç adımları',
                'ordering': ['order', 'id'],
            },
            bases=(main.models.Translatable, models.Model),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Ad')),
                ('kind', models.CharField(choices=[('client', 'İşveren'), ('certificate', 'Sertifika')], default='client', max_length=20, verbose_name='Tür')),
                ('logo', models.ImageField(blank=True, upload_to='references/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, verbose_name='Bağlantı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Referans',
                'verbose_name_plural': 'Referanslar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='after_image',
            field=models.ImageField(blank=True, upload_to='projects/ba/', verbose_name='Sonrası görseli'),
        ),
        migrations.AddField(
            model_name='project',
            name='before_image',
            field=models.ImageField(blank=True, upload_to='projects/ba/', verbose_name='Öncesi görseli'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Proje açıklaması (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Özet (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Başlık (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='summary_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Özet (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Başlık (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_en',
            field=models.TextField(blank=True, verbose_name='Hakkımızda (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_email',
            field=models.EmailField(blank=True, help_text='İletişim formu mesajları buraya iletilir. Boşsa yalnızca panele düşer.', max_length=254, verbose_name='Bildirim e-postası'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slogan (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Ülke kodu ile, ör. 905321234567. Boşsa buton gösterilmez.', max_length=40, verbose_name='WhatsApp numarası'),
        ),
    ]
